// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNfgNKXFAPdd4quR3jRCE2fJ4JqhaAPOY',
    appId: '1:545788962306:web:0cf69e14760001bb32291b',
    messagingSenderId: '545788962306',
    projectId: 'gatekeeper-8194e',
    authDomain: 'gatekeeper-8194e.firebaseapp.com',
    storageBucket: 'gatekeeper-8194e.appspot.com',
    measurementId: 'G-5J5ETD9SXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxxVEsWaD58CupPz88xlrYqPGXzaAMaA',
    appId: '1:545788962306:android:15cc2b0f30e2ea5b32291b',
    messagingSenderId: '545788962306',
    projectId: 'gatekeeper-8194e',
    storageBucket: 'gatekeeper-8194e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_ThZOqiUPGfKxbB-oV8mgpCuGSy1jvM',
    appId: '1:545788962306:ios:6b8055950cd605f932291b',
    messagingSenderId: '545788962306',
    projectId: 'gatekeeper-8194e',
    storageBucket: 'gatekeeper-8194e.appspot.com',
    iosBundleId: 'com.example.gateKeeperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_ThZOqiUPGfKxbB-oV8mgpCuGSy1jvM',
    appId: '1:545788962306:ios:6b8055950cd605f932291b',
    messagingSenderId: '545788962306',
    projectId: 'gatekeeper-8194e',
    storageBucket: 'gatekeeper-8194e.appspot.com',
    iosBundleId: 'com.example.gateKeeperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNfgNKXFAPdd4quR3jRCE2fJ4JqhaAPOY',
    appId: '1:545788962306:web:ccd04e70422231f732291b',
    messagingSenderId: '545788962306',
    projectId: 'gatekeeper-8194e',
    authDomain: 'gatekeeper-8194e.firebaseapp.com',
    storageBucket: 'gatekeeper-8194e.appspot.com',
    measurementId: 'G-6ED3X6DBPK',
  );
}
